# DO NOT EDIT THIS FILE!
#
# Python module ssr generated by omniidl

import omniORB
omniORB.updateModule("ssr")

# ** 1. Stub files contributing to this module
import leap_idl

# ** 2. Sub-modules

# ** 3. End
